name: PHPUnit

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install poppler
        run: sudo apt-get install poppler-utils
      - name: Install Dependencies
        run: composer i
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
